#Status constants
STATE_UNINITIALIZED=10
STATE_APPFILES_DEFINED=20
STATE_COMPLETED_FIRST_ROUND=30
STATE_CODE_UPDATE = 40
STATE_COMPLETED_ANALYSIS=50
STATE_INCORRECT_CODE_WRITE=60
STATE_INCORRECT_SUMMARY_WRITE=70
STATE_PENDING_CODE_WRITE=80
STATE_PENDING_SUMMARY_WRITE=90


SCAN_SUCCESS = 1000
ACTION_NOOP=10001
ACTION_FOLLOWUP=10002


LANGUAGE_RUBY='ruby'
LANGUAGE_ERB='erb'
LANGUAGE_HTML='html'
LANGUAGE_MARKDOWN='markdown'
